apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-wessel
  namespace: discord-bot-wessel
  labels:
    app: Discord-Bot
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: Discord-Bot
        octopusexport: OctopusExport
    spec:
      hostNetwork: false
      containers:
        - name: discord-bot-lavalink
          image: 'docker.jumpdrive.dev/discord-bot-lavalink:latest'
        - name: discord-bot-application
          image: 'docker.jumpdrive.dev/discord-bot:latest'
          env:
            - name: DISCORD_TOKEN
              value: abcdef
      imagePullSecrets:
        - name: docker-jumpdrive-secret
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
